Repository Programmiermethoden-CampusMinden/Prog2-Lecture, pull requests merged in 2022-05, with the labels that each got.

#370 Vorlesung: Testing: Mocking
  markdown/testing/mockito.md
  markdown/testing/src/mockito/.gitattributes
  markdown/testing/src/mockito/.gitignore
  markdown/testing/src/mockito/build.gradle
  markdown/testing/src/mockito/checkstyle.xml
  markdown/testing/src/mockito/gradle.properties
  markdown/testing/src/mockito/gradle/wrapper/gradle-wrapper.jar
  markdown/testing/src/mockito/gradle/wrapper/gradle-wrapper.properties
  markdown/testing/src/mockito/gradlew
  markdown/testing/src/mockito/gradlew.bat
  markdown/testing/src/mockito/src/main/java/fhb/LSF.java
  markdown/testing/src/mockito/src/main/java/fhb/Studi.java
  markdown/testing/src/mockito/src/main/java/wuppie/mock/IWuppiWarenlager.java
  markdown/testing/src/mockito/src/main/java/wuppie/mock/WuppiStore.java
  markdown/testing/src/mockito/src/main/java/wuppie/spy/IWuppiWarenlager.java
  markdown/testing/src/mockito/src/main/java/wuppie/spy/Wuppi.java
  markdown/testing/src/mockito/src/main/java/wuppie/spy/WuppiStore.java
  markdown/testing/src/mockito/src/main/java/wuppie/spy/WuppiWarenlager.java
  markdown/testing/src/mockito/src/main/java/wuppie/stub/IWuppiWarenlager.java
  markdown/testing/src/mockito/src/main/java/wuppie/stub/WuppiStore.java
  markdown/testing/src/mockito/src/main/java/wuppie/stub/WuppiWarenlagerStub.java
  markdown/testing/src/mockito/src/main/java/wuppie/verify/FluppisListe.java
  markdown/testing/src/mockito/src/test/java/fhb/MatcherTest.java
  markdown/testing/src/mockito/src/test/java/fhb/StudiMockTest.java
  markdown/testing/src/mockito/src/test/java/fhb/StudiSpyTest.java
  markdown/testing/src/mockito/src/test/java/fhb/StudiStubTest.java
  markdown/testing/src/mockito/src/test/java/fhb/VerifyTest.java
  markdown/testing/src/mockito/src/test/java/wuppie/mock/WuppiWarenlagerMockTest.java
  markdown/testing/src/mockito/src/test/java/wuppie/spy/WuppiWarenlagerSpyTest.java
  markdown/testing/src/mockito/src/test/java/wuppie/stub/WuppiWarenlagerStubTest.java
  markdown/testing/src/mockito/src/test/java/wuppie/verify/VerifyFluppisListeTest.java
  pm.bib
Labels: vorlesungen, w5

#447 Orga: Verstärke Hinweis im Lerntagebuch
  markdown/org/grading.md
  markdown/org/lerntagebuch.md
Labels: aufgaben, vorlesungen, w6

#448 Orga: Verstärke Hinweis zu Punkte-Nachtrag für Nachbearbeitung
  markdown/org/grading.md
Labels: aufgaben, vorlesungen, w6

#449 Orga: Keine Abzüge bei Tests (außer es wird in der Aufgabe gefordert)
  markdown/org/grading.md
Labels: aufgaben, vorlesungen, w6

#452 Orga: passe (Gesamt-) Punkte an (neue Test-Aufgaben im Dungeon)
  markdown/assignments/_index.md
  markdown/org/grading.md
Labels: aufgaben, vorlesungen, w6

#450 Dungeon-Aufgaben: Testen
  markdown/assignments/pool_dungeon/group_a/freie_aufgabe.md
  markdown/assignments/pool_dungeon/group_a/testen.md
  markdown/assignments/pool_dungeon/group_b/testen.md
  markdown/assignments/pool_dungeon/group_c/freie_aufgabe.md
  markdown/assignments/pool_dungeon/group_c/testen.md
Labels: aufgaben

#453 New Dungeon-Tasks: Fix Typos
  markdown/assignments/pool_dungeon/group_a/testen.md
  markdown/assignments/pool_dungeon/group_b/testen.md
  markdown/assignments/pool_dungeon/group_c/testen.md
Labels: bug, aufgaben, w6

#429 Vorlesung: Pattern: Observer
  markdown/pattern/images/lsf.png
  markdown/pattern/images/lsf.uxf
  markdown/pattern/images/observer.png
  markdown/pattern/images/observer.uxf
  markdown/pattern/images/observerexample.png
  markdown/pattern/images/observerexample.uxf
  markdown/pattern/observer.md
  markdown/pattern/src/observer/observer/LSF.java
  markdown/pattern/src/observer/observer/Lecturer.java
  markdown/pattern/src/observer/observer/Observer.java
  markdown/pattern/src/observer/observer/ObserverBeispiel.java
  markdown/pattern/src/observer/observer/Person.java
  markdown/pattern/src/observer/observer/Student.java
  markdown/pattern/src/observer/observer/Tutor.java
Labels: vorlesungen, w6

#431 Vorlesung: Pattern: Flyweight
  markdown/pattern/flyweight.md
  markdown/pattern/images/composite.drawio
  markdown/pattern/images/composite.png
  markdown/pattern/images/flyweight.drawio
  markdown/pattern/images/flyweight.png
  pm.bib
Labels: vorlesungen, w6

#458 Add task for type-object pattern
  markdown/assignments/pool_concept/tasks/type-object.md
Labels: aufgaben, w6

#428 Vorlesung: Pattern: Type Object
  markdown/pattern/type-object.md
Labels: vorlesungen, w6

#433 Vorlesung: Java/JVM: Enumerationen
  markdown/java-jvm/enums.md
  markdown/java-jvm/src/enums/FinalDemo.java
  markdown/java-jvm/src/enums/v1/Studi.java
  markdown/java-jvm/src/enums/v2/Studi.java
  markdown/java-jvm/src/enums/v3/Fach.java
  markdown/java-jvm/src/enums/v3/Studi.java
Labels: vorlesungen, w6

#434 Aufgaben: Überarbeite Sheet 06
  markdown/assignments/pool_concept/sheet06.md
Labels: aufgaben, w6

#459 Update: Konzeptaufgabe Mocking
  markdown/assignments/pool_concept/tasks/mocking.md
Labels: bug, aufgaben, w5

#440 Vorlesung: Pattern: Singleton
  data/schedule.yaml
  markdown/pattern/singleton.md
  markdown/pattern/src/singleton/SingletonEager.java
  markdown/pattern/src/singleton/SingletonLazy.java
Labels: vorlesungen, w6

#462 VL Observer: fix code snippets folder
  markdown/pattern/src/observer/LSF.java
  markdown/pattern/src/observer/Lecturer.java
  markdown/pattern/src/observer/Observer.java
  markdown/pattern/src/observer/ObserverBeispiel.java
  markdown/pattern/src/observer/Person.java
  markdown/pattern/src/observer/Student.java
  markdown/pattern/src/observer/Tutor.java
Labels: bug, vorlesungen, w6

#324 Vorlesung: Java/JVM: Reflection
  markdown/java-jvm/reflection.md
  markdown/java-jvm/src/reflection/ClassLoaderDemo.java
  markdown/java-jvm/src/reflection/ReflectionDemo.java
  markdown/java-jvm/src/reflection/Studi.java
  markdown/java-jvm/src/reflection/Wuppie.java
Labels: vorlesungen, w7

#466 Konzeptaufgabe: Template Method Pattern
  markdown/assignments/pool_concept/tasks/template_method_pattern.md
Labels: aufgaben, w7

#467 Add: Konzeptaufgabe: Serialisierung
  markdown/assignments/pool_concept/tasks/images/uml_serialisierung.png
  markdown/assignments/pool_concept/tasks/images/uml_serialisierung.uxf
  markdown/assignments/pool_concept/tasks/serialisierung.md
Labels: aufgaben, w7

#470 Add: Konzeptaufgabe Annotations
  markdown/assignments/pool_concept/tasks/annotations.md
Labels: aufgaben

#471 Add: Konzeptaufgabe Defaultmethoden
  markdown/assignments/pool_concept/tasks/defaultmethoden.md
Labels: aufgaben, w9, tutorium

#472 Add Konzeptaufgabe Reflection
  markdown/assignments/pool_concept/tasks/relection.md
Labels: aufgaben, w7

#432 Vorlesung: Java/JVM: Serialisierung
  markdown/java-jvm/serialisation.md
  markdown/java-jvm/src/serial/SerializableStudi.java
  markdown/java-jvm/src/serial/TestSerializableStudi.java
Labels: vorlesungen, w7

#469 Vorlesung: Pattern: Template-Method
  markdown/pattern/images/template-method.drawio
  markdown/pattern/images/template-method.png
  markdown/pattern/template-method.md
Labels: vorlesungen, w7

#468 Aufgaben: Überarbeite Sheet 07
  markdown/assignments/pool_concept/sheet07.md
  markdown/assignments/pool_concept/tasks/reflection.md
Labels: aufgaben, w7

#473 Lecture Serialisation: fix link to demo code
  markdown/java-jvm/serialisation.md
Labels: bug, vorlesungen, w7

#325 Vorlesung: GUI: Swing
  data/schedule.yaml
  markdown/gui/basics.md
  markdown/gui/events.md
  markdown/gui/images/ActionListener.png
  markdown/gui/images/ActionListener.uxf
  markdown/gui/images/EventListener.png
  markdown/gui/images/EventListener.uxf
  markdown/gui/images/EventObject.png
  markdown/gui/images/EventObject.uxf
  markdown/gui/images/mvc.drawio
  markdown/gui/images/mvc.png
  markdown/gui/images/screenshot-borderlayout.png
  markdown/gui/images/screenshot-dialog.png
  markdown/gui/images/screenshot-filechooser.png
  markdown/gui/images/screenshot-flowlayout.png
  markdown/gui/images/screenshot-gridlayout.png
  markdown/gui/images/screenshot-radiobuttons.png
  markdown/gui/layouts.md
  markdown/gui/src/basics/FirstWindow.java
  markdown/gui/src/basics/SecondWindow.java
  markdown/gui/src/events/DemoStarter.java
  markdown/gui/src/events/ListenerDemo.java
  markdown/gui/src/events/MouseAdapterDemo.java
  markdown/gui/src/events/MouseListenerDemo.java
  markdown/gui/src/layout/Border.java
  markdown/gui/src/layout/DemoStarter.java
  markdown/gui/src/layout/Flow.java
  markdown/gui/src/layout/Grid.java
  markdown/gui/src/layout/GridBag.java
  markdown/gui/src/tables/DemoStarter.java
  markdown/gui/src/tables/ModelTable.java
  markdown/gui/src/tables/SelectTable.java
  markdown/gui/src/tables/SimpleTable.java
  markdown/gui/src/widgets/DemoStarter.java
  markdown/gui/src/widgets/DialogDemo.java
  markdown/gui/src/widgets/FileChooserDemo.java
  markdown/gui/src/widgets/MenuDemo.java
  markdown/gui/src/widgets/PopupDemo.java
  markdown/gui/src/widgets/RadioButtonDemo.java
  markdown/gui/src/widgets/TabbedPaneDemo.java
  markdown/gui/swing.md
  markdown/gui/tables.md
  markdown/gui/widgets.md
  markdown/images/fahrplan.png
  planung_pm.xlsx
Labels: vorlesungen, w8

#326 Vorlesung: GUI: Java2D
  markdown/gui/images/java2d-koordinaten.png
  markdown/gui/images/java2d.png
  markdown/gui/images/observer.png
  markdown/gui/images/observer.uxf
  markdown/gui/java2d.md
  markdown/gui/src/java2d/DemoStarter.java
  markdown/gui/src/java2d/SimpleDrawings.java
  markdown/gui/src/java2d/SimpleFonts.java
  markdown/gui/src/java2d/SimplePoly.java
  markdown/gui/src/java2d/simplegame/GameObject.java
  markdown/gui/src/java2d/simplegame/GameOval.java
  markdown/gui/src/java2d/simplegame/GameRect.java
  markdown/gui/src/java2d/simplegame/GameString.java
  markdown/gui/src/java2d/simplegame/J2DTeaser.java
Labels: vorlesungen, w8

#483 [VL] Swing/Layout-Manager: Improve Intro/Outro
  markdown/gui/layouts.md
Labels: bug, vorlesungen, w9

#486 [VL] Frameworks: add Quiz
  markdown/frameworks/intro.md
Labels: enhancement, vorlesungen, w9

#493 Add: Konzeptaufgabe RegExp
  markdown/assignments/pool_concept/tasks/regexp.md
Labels: aufgaben

#494 Add: Konzeptaufgabe: Funktionsinterfaces, Lambdas und Methodenreferenzen
  markdown/assignments/pool_concept/tasks/lambda.md
Labels: aufgaben

#490 Vorlesung: Modern Java: Defaultmethoden
  markdown/modern-java/defaultmethods.md
  markdown/modern-java/src/defaultmethods/quiz/DefaultTest.java
  markdown/modern-java/src/defaultmethods/rule1/DefaultTest1.java
  markdown/modern-java/src/defaultmethods/rule2/DefaultTest2.java
  markdown/modern-java/src/defaultmethods/rule3/DefaultTest3.java
Labels: vorlesungen, w9

#484 Konzeptaufgabe: Sheet08
  markdown/assignments/pool_concept/sheet08.md
Labels: aufgaben, w9

#489 Vorlesung: Modern Java: Funktionsinterfaces und Lambdas
  data/schedule.yaml
  markdown/modern-java/lambdas.md
  markdown/modern-java/src/nested/DemoAnonymousInnerClass.java
  markdown/modern-java/src/nested/DemoComparator.java
  markdown/modern-java/src/nested/DemoFunctionalInterface.java
  markdown/modern-java/src/nested/DemoLambda.java
  markdown/modern-java/src/nested/Outer.java
  markdown/modern-java/src/nested/Studi.java
  markdown/modern-java/src/nested/StudiListNested.java
  markdown/modern-java/src/nested/Wuppie.java
Labels: vorlesungen, w9

#487 Vorlesung: Java/JVM: RegExp
  markdown/java-jvm/regexp.md
  markdown/java-jvm/src/regexp/Backref.java
  markdown/java-jvm/src/regexp/Groups.java
  markdown/java-jvm/src/regexp/MatchFind.java
  markdown/java-jvm/src/regexp/Quantifier.java
  markdown/java-jvm/src/regexp/StringSplit.java
Labels: vorlesungen, w9

#497 [Org] Note&Credits: Klarstellung Themen und Notenspiegel E1/E2
  markdown/org/grading.md
Labels: bug, vorlesungen, w9

#503 [VL] Add quizzes to RegExp and Method References
  markdown/java-jvm/regexp.md
  markdown/modern-java/methodreferences.md
Labels: bug, vorlesungen, quizzes, w8
