Repository Programmiermethoden-CampusMinden/Prog2-Lecture, pull requests merged in 2022-03, with the labels that each got.

#146 Add new assignments (folder structure)
  markdown/assignments/_index.md
  markdown/assignments/pool_a/_index.md
  markdown/assignments/pool_a/charakterklassen/index.md
  markdown/assignments/pool_a/crafting/index.md
  markdown/assignments/pool_a/fallen/index.md
  markdown/assignments/pool_a/inventar_text_based/index.md
  markdown/assignments/pool_a/skills/index.md
  markdown/assignments/pool_a/speichern_und_laden/index.md
  markdown/assignments/pool_a/start/index.md
  markdown/assignments/pool_b/_index.md
  markdown/assignments/pool_b/boss_monster/index.md
  markdown/assignments/pool_b/energiepunkte/index.md
  markdown/assignments/pool_b/fernkampf/index.md
  markdown/assignments/pool_b/magie/index.md
  markdown/assignments/pool_b/monster/index.md
  markdown/assignments/pool_b/nahkampf/index.md
  markdown/assignments/pool_b/schlaue_monster/index.md
  markdown/assignments/pool_b/xp/index.md
  markdown/assignments/pool_c/_index.md
  markdown/assignments/pool_c/dialogsystem/index.md
  markdown/assignments/pool_c/hud/index.md
  markdown/assignments/pool_c/inventar_ui/index.md
  markdown/assignments/pool_c/item/index.md
  markdown/assignments/pool_c/npc/index.md
  markdown/assignments/pool_c/quests/index.md
  markdown/assignments/pool_c/schatzkiste/index.md
  markdown/assignments/pool_c/shop/index.md
  markdown/assignments/pool_c/taschen/index.md
  markdown/assignments/pool_k/_index.md
  markdown/assignments/pool_k/sheet01/index.md
  markdown/assignments/pool_k/sheet02/index.md
  markdown/assignments/pool_k/sheet03/index.md
  markdown/assignments/pool_k/sheet04/index.md
  markdown/assignments/pool_k/sheet05/index.md
  markdown/assignments/pool_k/sheet06/index.md
  markdown/assignments/pool_k/sheet07/index.md
  markdown/assignments/pool_k/sheet08/index.md
  markdown/assignments/pool_k/sheet09/index.md
  markdown/assignments/pool_k/sheet10/index.md
  markdown/assignments/pool_p/_index.md
  markdown/assignments/pool_p/projekt1/index.md
  markdown/assignments/pool_p/projekt2/index.md
  markdown/assignments/sheet01.md
  markdown/assignments/sheet02/index.md
Labels: aufgaben

#195 upgrade hugo to 0.93.1 (bugfixes)
  .github/actions/alpine-pandoc-hugo/install-packages.sh
Labels: pandoc

#197 workflow slides: build only on master and manually triggered
  .github/workflows/hugo.yaml
  .github/workflows/slides.yaml
Labels: pandoc

#199 Worklows: Update actions/checkout to v3
  .github/workflows/hugo.yaml
  .github/workflows/slides.yaml
Labels: pandoc

#284 Makefile: fix handling of shared image folders for single markdown files (slides)
  Makefile
Labels: pandoc

#288 Gitignore: add .vscode and .idea to gitignore
  .gitignore
Labels: pandoc

#281 Vorlesung: Literatur
  pm.bib
Labels: vorlesungen

#276 Planung: Tausche Woche 8 und Woche 12, Vorlesung ist jetzt am Freitag
  config.yaml
  data/schedule.yaml
  planung_pm.xlsx
Labels: aufgaben, vorlesungen

#335 add folder and landing page for tasks
  markdown/assignments/pool_k/tasks/_index.md
Labels: aufgaben

#200 Vorlesung: Git Intro
  markdown/git/images/centralised.png
  markdown/git/images/distributed.png
  markdown/git/images/lifecycle.png
  markdown/git/images/local.png
  markdown/git/images/screenshot_branches.png
  markdown/git/images/screenshot_merge-request_code.png
  markdown/git/images/screenshot_merge-request_discussion.png
  markdown/git/images/screenshot_zusammenarbeit_ohne_vcs.png
  markdown/git/images/workflow.png
  markdown/git/images/workflow_remote.png
  markdown/git/intro.md
Labels: vorlesungen

#201 Vorlesung: Git Basics
  markdown/git/basics.md
Labels: vorlesungen

#259 Vorlesung: Git Branches
  markdown/git/branches.md
Labels: vorlesungen

#260 Vorlesung: Git Branchingstrategien
  markdown/git/branching-strategies.md
Labels: vorlesungen

#261 Vorlesung: Git Remotes
  markdown/git/remotes.md
Labels: vorlesungen

#278 Vorlesung: Git Workflows
  markdown/git/workflows.md
Labels: vorlesungen

#280 Vorlesung: Git Bisect
  markdown/git/bisect.md
Labels: vorlesungen

#285 Vorlesung: Logging
  markdown/coding/images/logging.png
  markdown/coding/logging.md
  markdown/coding/src/logging/LoggingDemo.java
  markdown/coding/src/logging/LoggingHandler.java
  markdown/coding/src/logging/LoggingLevel.java
  markdown/coding/src/logging/LoggingParent.java
  markdown/coding/src/logging/MyFormatter.java
Labels: vorlesungen

#330 Vorlesung: Javadoc
  markdown/coding/javadoc.md
Labels: vorlesungen

#286 Vorlesung: Factory-Method Pattern
  markdown/pattern/factory-method.md
  markdown/pattern/images/factorymethod.png
  markdown/pattern/images/factorymethod.uxf
  markdown/pattern/src/factory/FactoryBeispiel.java
Labels: vorlesungen

#289 Vorlesung: Generics: Klassen und Methoden
  markdown/generics/classes-methods.md
  markdown/generics/src/classes/GenericClasses.java
  markdown/generics/src/methods/GenericMethods.java
Labels: vorlesungen

#290 Vorlesung: Generics: Bounds und Wildcards
  markdown/generics/bounds-wildcards.md
  markdown/generics/src/bounds/Cps.java
  markdown/generics/src/wildcards/v1/X.java
  markdown/generics/src/wildcards/v2/X.java
  markdown/generics/src/wildcards/v3/X.java
Labels: vorlesungen

#291 Vorlesung: Generics: Type Erasure
  markdown/generics/type-erasure.md
Labels: vorlesungen

#340 Readme: add link to workflow (wiki)
  README.md
Labels: aufgaben, vorlesungen

#343 Vorlesung: add sketch=true and improve templates (youtube, fhmedia, quizzes)
  markdown/building/ant.md
  markdown/building/ci.md
  markdown/building/docker.md
  markdown/building/gradle.md
  markdown/building/maven.md
  markdown/coding/debugging.md
  markdown/coding/javadoc.md
  markdown/coding/logging.md
  markdown/coding/refactoring.md
  markdown/coding/smells.md
  markdown/coding/tdd.md
  markdown/database/jdbc.md
  markdown/frameworks/guava.md
  markdown/generics/bounds-wildcards.md
  markdown/generics/classes-methods.md
  markdown/generics/generics-polymorphism.md
  markdown/generics/type-erasure.md
  markdown/git/basics.md
  markdown/git/bisect.md
  markdown/git/branches.md
  markdown/git/branching-strategies.md
  markdown/git/intro.md
  markdown/git/remotes.md
  markdown/git/workflows.md
  markdown/gui/java2d.md
  markdown/gui/swing.md
  markdown/java-jvm/annotations.md
  markdown/java-jvm/collections.md
  markdown/java-jvm/configuration.md
  markdown/java-jvm/enums.md
  markdown/java-jvm/exceptions.md
  markdown/java-jvm/reflection.md
  markdown/java-jvm/regexp.md
  markdown/java-jvm/serialisation.md
  markdown/modern-java/defaultmethods.md
  markdown/modern-java/lambdas.md
  markdown/modern-java/methodreferences.md
  markdown/modern-java/optional.md
  markdown/modern-java/records.md
  markdown/modern-java/stream-api.md
  markdown/pattern/command.md
  markdown/pattern/factory-method.md
  markdown/pattern/flyweight.md
  markdown/pattern/observer.md
  markdown/pattern/strategy.md
  markdown/pattern/template-method.md
  markdown/pattern/type-object.md
  markdown/pattern/visitor.md
  markdown/testing/junit-basics.md
  markdown/testing/mockito.md
  markdown/testing/testcases.md
  markdown/threads/highlevel.md
  markdown/threads/intro.md
  markdown/threads/synchronisation.md
Labels: vorlesungen

#341 Add: Konzeptaufgabe GitBasic
  markdown/assignments/pool_k/tasks/git_basics.md
Labels: aufgaben, w1

#342 Add: Konzeptaufgabe Git Branches
  markdown/assignments/pool_k/tasks/git_branches.md
Labels: aufgaben, w1

#349 Aufgaben: Überarbeite Sheet 01
  markdown/assignments/pool_k/sheet01/index.md
Labels: aufgaben, w1

#316 Orga: Syllabus
  markdown/_index.md
  markdown/org/images/modulbeschreibung.png
  markdown/org/schedule.md
  markdown/org/syllabus.md
Labels: aufgaben, vorlesungen, w1

#318 Orga: Ressourcen
  markdown/assignments/pool_k/sheet01/index.md
  markdown/org/resources.md
  pm.bib
Labels: aufgaben, vorlesungen, w1

#348 Aufgaben: Überarbeite Landing-Pages
  markdown/assignments/_index.md
  markdown/assignments/pool_a/_index.md
  markdown/assignments/pool_b/_index.md
  markdown/assignments/pool_c/_index.md
  markdown/assignments/pool_k/_index.md
Labels: aufgaben, w1

#354 Planung: Verbessere Darstellung Abgaben (Praktikum)
  data/schedule.yaml
  markdown/assignments/pool_k/sheet01.md
  markdown/assignments/pool_k/sheet02.md
  markdown/assignments/pool_k/sheet03.md
  markdown/assignments/pool_k/sheet04.md
  markdown/assignments/pool_k/sheet05.md
  markdown/assignments/pool_k/sheet05/index.md
  markdown/assignments/pool_k/sheet06.md
  markdown/assignments/pool_k/sheet07.md
  markdown/assignments/pool_k/sheet07/index.md
  markdown/assignments/pool_k/sheet08.md
  markdown/assignments/pool_k/sheet09.md
  markdown/assignments/pool_k/sheet09/index.md
  markdown/assignments/pool_k/sheet10.md
  markdown/assignments/pool_k/tasks/git_basics.md
  markdown/assignments/pool_k/tasks/git_branches.md
Labels: aufgaben, vorlesungen, w1

#355 Generics2: fix slide title (hands-on)
  markdown/generics/bounds-wildcards.md
Labels: vorlesungen, w3

#344 Add: Konzeptaufgabe JUnit Basics
  markdown/assignments/pool_k/tasks/junit_basics.md
Labels: aufgaben

#359 Generics2: Fix title for quiz
  markdown/generics/bounds-wildcards.md
Labels: vorlesungen

#270 Aufgabe: Pool A: Skills
  markdown/assignments/pool_a/skills/index.md
Labels: aufgaben

#273 Aufgabe: Pool A: Fallen
  markdown/assignments/pool_a/fallen/index.md
Labels: aufgaben

#268 Aufgabe: Pool A: Inventar (text based)
  markdown/assignments/pool_a/inventar_text_based/index.md
Labels: aufgaben

#275 Aufgabe: Pool A: Crafting
  markdown/assignments/pool_a/crafting/index.md
Labels: aufgaben

#269 Aufgabe: Pool A: Charakterklassen
  markdown/assignments/pool_a/charakterklassen/index.md
Labels: aufgaben

#296 Aufgabe: Pool B: Monster
  markdown/assignments/pool_b/monster/index.md
Labels: aufgaben

#297 Aufgabe: Pool B: Nahkampf
  markdown/assignments/pool_b/nahkampf/index.md
Labels: aufgaben

#295 Aufgabe: Pool B: Energiepunkte/Game-Over
  markdown/assignments/pool_b/energiepunkte/index.md
  markdown/assignments/pool_b/gameover/index.md
Labels: aufgaben

#300 Aufgabe: Pool B: Magie
  markdown/assignments/pool_b/magie/index.md
Labels: aufgaben

#302 Aufgabe: Pool B: XP
  markdown/assignments/pool_b/xp/index.md
Labels: aufgaben

#304 Aufgabe: Pool B: Schlaue Monster
  markdown/assignments/pool_b/schlaue_monster/index.md
Labels: aufgaben

#305 Aufgabe: Pool B: Boss Monster
  markdown/assignments/pool_b/boss_monster/index.md
Labels: aufgaben

#306 Aufgabe: Pool C: Item
  markdown/assignments/pool_c/item/index.md
Labels: aufgaben

#307 Aufgabe: Pool C: Taschen
  markdown/assignments/pool_c/taschen/index.md
Labels: aufgaben

#310 Aufgabe: Pool C: HUD
  markdown/assignments/pool_c/hud/index.md
Labels: aufgaben

#311 Aufgabe: Pool C: Inventar UI
  markdown/assignments/pool_c/inventar_ui/index.md
Labels: aufgaben

#312 Aufgabe: Pool C: NPC
  markdown/assignments/pool_c/npc/index.md
Labels: aufgaben

#313 Aufgabe: Pool C: Dialogsystem
  markdown/assignments/pool_c/dialogsystem/index.md
Labels: aufgaben

#314 Aufgabe: Pool C: Quests
  markdown/assignments/pool_c/quests/index.md
Labels: aufgaben

#315 Aufgabe: Pool C: Shop
  markdown/assignments/pool_c/shop/index.md
Labels: aufgaben

#362 Aufgaben: Stelle auf Single-Markdown-Files um
  markdown/assignments/pool_a/charakterklassen.md
  markdown/assignments/pool_a/crafting.md
  markdown/assignments/pool_a/fallen.md
  markdown/assignments/pool_a/inventar_text_based.md
  markdown/assignments/pool_a/skills.md
  markdown/assignments/pool_a/speichern_und_laden.md
  markdown/assignments/pool_a/start.md
  markdown/assignments/pool_b/boss_monster.md
  markdown/assignments/pool_b/fernkampf.md
  markdown/assignments/pool_b/gameover.md
  markdown/assignments/pool_b/magie.md
  markdown/assignments/pool_b/monster.md
  markdown/assignments/pool_b/nahkampf.md
  markdown/assignments/pool_b/schlaue_monster.md
  markdown/assignments/pool_b/xp.md
  markdown/assignments/pool_c/dialogsystem.md
  markdown/assignments/pool_c/hud.md
  markdown/assignments/pool_c/inventar_ui.md
  markdown/assignments/pool_c/item.md
  markdown/assignments/pool_c/npc.md
  markdown/assignments/pool_c/quests.md
  markdown/assignments/pool_c/schatzkiste.md
  markdown/assignments/pool_c/shop.md
  markdown/assignments/pool_c/taschen.md
Labels: aufgaben, pandoc

#363 Aufgaben: fix weird whitespace problem
  markdown/assignments/pool_a/charakterklassen.md
  markdown/assignments/pool_a/skills.md
  markdown/assignments/pool_a/speichern_und_laden.md
  markdown/assignments/pool_b/boss_monster.md
  markdown/assignments/pool_b/fernkampf.md
  markdown/assignments/pool_b/gameover.md
  markdown/assignments/pool_b/magie.md
  markdown/assignments/pool_b/monster.md
  markdown/assignments/pool_b/nahkampf.md
  markdown/assignments/pool_b/xp.md
  markdown/assignments/pool_c/hud.md
  markdown/assignments/pool_c/item.md
  markdown/assignments/pool_c/schatzkiste.md
  markdown/org/resources.md
Labels: bug, aufgaben, pandoc

#364 Fix Aufgaben: s/Andre/André
  markdown/assignments/pool_a/charakterklassen.md
  markdown/assignments/pool_a/crafting.md
  markdown/assignments/pool_a/fallen.md
  markdown/assignments/pool_a/freie_aufgabe.md
  markdown/assignments/pool_a/inventar_text_based.md
  markdown/assignments/pool_a/skills.md
  markdown/assignments/pool_a/speichern_und_laden.md
  markdown/assignments/pool_a/start.md
  markdown/assignments/pool_b/boss_monster.md
  markdown/assignments/pool_b/fernkampf.md
  markdown/assignments/pool_b/freie_aufgabe.md
  markdown/assignments/pool_b/gameover.md
  markdown/assignments/pool_b/magie.md
  markdown/assignments/pool_b/monster.md
  markdown/assignments/pool_b/nahkampf.md
  markdown/assignments/pool_b/schlaue_monster.md
  markdown/assignments/pool_b/xp.md
  markdown/assignments/pool_c/dialogsystem.md
  markdown/assignments/pool_c/freie_aufgabe.md
  markdown/assignments/pool_c/hud.md
  markdown/assignments/pool_c/inventar_ui.md
  markdown/assignments/pool_c/item.md
  markdown/assignments/pool_c/npc.md
  markdown/assignments/pool_c/quests.md
  markdown/assignments/pool_c/schatzkiste.md
  markdown/assignments/pool_c/shop.md
  markdown/assignments/pool_c/taschen.md
  markdown/assignments/pool_k/_index.md
  markdown/assignments/pool_k/sheet01.md
  markdown/assignments/pool_k/sheet02.md
  markdown/assignments/pool_k/sheet03.md
  markdown/assignments/pool_k/sheet04.md
  markdown/assignments/pool_k/sheet05.md
  markdown/assignments/pool_k/sheet06.md
  markdown/assignments/pool_k/sheet07.md
  markdown/assignments/pool_k/sheet08.md
  markdown/assignments/pool_k/sheet09.md
  markdown/assignments/pool_k/sheet10.md
Labels: aufgaben
