Repository Programmiermethoden-CampusMinden/Prog2-Lecture, pull requests merged in 2022-06, with the labels that each got.

#505 Add Konzeptaufgabe: Visitor Pattern
  markdown/assignments/pool_concept/tasks/visitor_pattern.md
Labels: aufgaben

#498 Aufgaben: Überarbeite Sheet 09
  markdown/assignments/pool_concept/sheet09.md
Labels: aufgaben, w10

#500 Vorlesung: Pattern: Visitor
  markdown/pattern/images/parsetree.png
  markdown/pattern/images/parsetree_classes_uml.drawio
  markdown/pattern/images/parsetree_classes_uml.png
  markdown/pattern/images/parsetree_eval_print_uml.drawio
  markdown/pattern/images/parsetree_eval_print_uml.png
  markdown/pattern/images/parsetree_eval_uml.drawio
  markdown/pattern/images/parsetree_eval_uml.png
  markdown/pattern/images/parsetree_visitor_uml.drawio
  markdown/pattern/images/parsetree_visitor_uml.png
  markdown/pattern/images/visitor.drawio
  markdown/pattern/images/visitor.png
  markdown/pattern/src/visitor/direct/AddExpr.java
  markdown/pattern/src/visitor/direct/DemoExpr.java
  markdown/pattern/src/visitor/direct/Expr.java
  markdown/pattern/src/visitor/direct/MulExpr.java
  markdown/pattern/src/visitor/direct/NumExpr.java
  markdown/pattern/src/visitor/visit/extrav/AddExpr.java
  markdown/pattern/src/visitor/visit/extrav/DemoExpr.java
  markdown/pattern/src/visitor/visit/extrav/EvalVisitor.java
  markdown/pattern/src/visitor/visit/extrav/Expr.java
  markdown/pattern/src/visitor/visit/extrav/ExprVisitor.java
  markdown/pattern/src/visitor/visit/extrav/MulExpr.java
  markdown/pattern/src/visitor/visit/extrav/NumExpr.java
  markdown/pattern/src/visitor/visit/extrav/PrintVisitor.java
  markdown/pattern/src/visitor/visit/intrav/AddExpr.java
  markdown/pattern/src/visitor/visit/intrav/DemoExpr.java
  markdown/pattern/src/visitor/visit/intrav/EvalVisitor.java
  markdown/pattern/src/visitor/visit/intrav/Expr.java
  markdown/pattern/src/visitor/visit/intrav/ExprVisitor.java
  markdown/pattern/src/visitor/visit/intrav/MulExpr.java
  markdown/pattern/src/visitor/visit/intrav/NumExpr.java
  markdown/pattern/src/visitor/visit/intrav/PrintVisitor.java
  markdown/pattern/visitor.md
Labels: vorlesungen, w10

#499 Vorlesung: Pattern: Command-Pattern
  markdown/pattern/command.md
  markdown/pattern/images/command.drawio
  markdown/pattern/images/command.png
  markdown/pattern/src/command/sketch/Buttons.java
  markdown/pattern/src/command/sketch/Command.java
  markdown/pattern/src/command/sketch/Entity.java
  markdown/pattern/src/command/sketch/Hero.java
  markdown/pattern/src/command/sketch/InputHandler.java
  markdown/pattern/src/command/sketch/InputHandler2.java
  markdown/pattern/src/command/sketch/Jump.java
  markdown/pattern/src/command/undo/Buttons.java
  markdown/pattern/src/command/undo/Command.java
  markdown/pattern/src/command/undo/Entity.java
  markdown/pattern/src/command/undo/Hero.java
  markdown/pattern/src/command/undo/InputHandler3.java
  markdown/pattern/src/command/undo/Jump.java
  markdown/pattern/src/command/undo/Move.java
Labels: vorlesungen, w10

#502 Vorlesung: Modern Java: Records
  markdown/modern-java/records.md
  markdown/modern-java/src/records/DemoRecords.java
  markdown/modern-java/src/records/Studi.java
  markdown/modern-java/src/records/StudiR.java
  markdown/modern-java/src/records/StudiS.java
  markdown/modern-java/src/records/StudiT.java
Labels: vorlesungen, w10

#501 [VL] Modern Java: Optional
  data/schedule.yaml
  markdown/modern-java/optional.md
  markdown/modern-java/src/optional/streams/Demo.java
  markdown/modern-java/src/optional/streams/LSF.java
  markdown/modern-java/src/optional/streams/Studi.java
  markdown/modern-java/src/optional/teaser/Demo.java
  markdown/modern-java/src/optional/teaser/LSF.java
  markdown/modern-java/src/optional/teaser/Studi.java
  markdown/modern-java/src/optional/traditional/Demo.java
  markdown/modern-java/src/optional/traditional/LSF.java
  markdown/modern-java/src/optional/traditional/Studi.java
Labels: vorlesungen, w10

#518 [VL] Quiz für Streams nachreichen
  markdown/modern-java/stream-api.md
Labels: bug, vorlesungen, quizzes, w10

#524 [VL] Quiz für Record-Klassen nachreichen
  markdown/modern-java/records.md
Labels: bug, vorlesungen, w10

#525 [VL] Hinweis: Record-Klassen sind final
  markdown/modern-java/records.md
Labels: bug, vorlesungen, w10

#526 [VL] Quiz für Optional nachreichen
  markdown/modern-java/optional.md
Labels: bug, vorlesungen, w10

#527 [VL] Update schedule
  data/schedule.yaml
  markdown/images/fahrplan.png
Labels: enhancement, aufgaben, vorlesungen, quizzes

#528 Add: Konzeptaufgabe Optional
  markdown/assignments/pool_concept/tasks/optional.md
Labels: aufgaben, w12, tutorium

#519 [VL] Threads: Intro
  markdown/threads/images/ThreadRunnable.png
  markdown/threads/images/ThreadRunnable.uxf
  markdown/threads/images/screenshot_swingworker.png
  markdown/threads/intro.md
  markdown/threads/src/creation/ThreadRunnable.java
  markdown/threads/src/creation/ThreadedKaputt.java
  markdown/threads/src/intro/Join.java
  markdown/threads/src/intro/Threaded.java
  markdown/threads/src/intro/Traditional.java
  markdown/threads/src/misc/SwingWorkerDemo.java
  pm.bib
Labels: vorlesungen, überarbeiten, w11

#520 [VL] Threads: Synchronisierung
  markdown/threads/src/synchronised/Deadlock.java
  markdown/threads/src/synchronised/MethodSync.java
  markdown/threads/src/synchronised/ObjSync.java
  markdown/threads/src/synchronised/Staffel.java
  markdown/threads/src/synchronised/Teaser.java
  markdown/threads/synchronisation.md
Labels: vorlesungen, überarbeiten, w11

#510 [VL] Exception
  markdown/java-jvm/exceptions.md
  markdown/java-jvm/images/exception.png
  markdown/java-jvm/images/exception.uxf
  markdown/java-jvm/src/exceptions/DivExample.java
  markdown/java-jvm/src/exceptions/HowMuchTry.java
  markdown/java-jvm/src/exceptions/MyCheckedException.java
  markdown/java-jvm/src/exceptions/MyUncheckedException.java
  markdown/java-jvm/src/exceptions/WhereToCatch.java
Labels: vorlesungen, neu, w11

#534 Add: Konzeptaufgae Exceptions
  markdown/assignments/pool_concept/tasks/exceptions.md
Labels: aufgaben, tutorium

#538 [VL] Quiz für Exceptions nachreichen
  markdown/java-jvm/exceptions.md
Labels: bug, vorlesungen, quizzes, w11

#539 Add: Aufgabe: Multithreading
  markdown/assignments/pool_concept/tasks/multithreading.md
Labels: aufgaben, high prio

#522 Aufgaben: Überarbeite Sheet 10
  markdown/assignments/pool_concept/sheet10.md
Labels: aufgaben, neu, w11, high prio

#541 [VL] remove demo javascript
  markdown/coding/javadoc.md
Labels: bug, vorlesungen

#542 [VL] final rescheduling: move collections to last week
  data/schedule.yaml
  markdown/images/fahrplan.png
  planung_pm.xlsx
Labels: bug, vorlesungen

#536 [VL] Build: Ant
  markdown/building/ant.md
  markdown/building/src/Dockerfile
  markdown/building/src/Makefile
  markdown/building/src/ant/Hello.java
  markdown/building/src/ant/build.xml
  markdown/building/src/ant/hello.xml
  markdown/building/src/ant/ivy.xml
  markdown/building/src/ant/ivydemo.xml
Labels: vorlesungen, überarbeiten, w12

#537 [VL] Build: Maven
  markdown/building/images/screenshot_maven-lifecycle.png
  markdown/building/images/screenshot_maven-project.png
  markdown/building/maven.md
  markdown/building/src/maven/Hello.java
  markdown/building/src/maven/pom.xml
Labels: vorlesungen, überarbeiten, w12

#396 [VL] Build: Docker
  markdown/building/docker.md
  markdown/building/images/virtualisierung.png
  markdown/building/images/vscode-remote.png
  markdown/building/src/docker/.github/workflows/demo.yml
  markdown/building/src/docker/.gitlab-ci.yml
  markdown/building/src/docker/Hello.java
  markdown/building/src/docker/debian-latex.df
Labels: vorlesungen, neu, w12

#535 [VL] Java/JVM: Configuration
  markdown/java-jvm/configuration.md
  markdown/java-jvm/images/ide-cli.png
  markdown/java-jvm/src/cli/Args.java
  markdown/java-jvm/src/cli/Props.java
  markdown/java-jvm/src/cli/Teaser.java
Labels: vorlesungen, neu, w12

#546 [VL] Quiz für Build: Maven nachreichen
  markdown/building/maven.md
Labels: bug, vorlesungen, quizzes, w12

#547 [VL] Maven: fix url and tldr
  markdown/building/maven.md
Labels: bug, vorlesungen, w12

#548 [VL] Configuration: fix readings
  markdown/java-jvm/configuration.md
Labels: bug, vorlesungen, w12

#549 [VL] Quiz für Threads: High-Level Konzepte nachreichen
  markdown/threads/highlevel.md
Labels: bug, vorlesungen, quizzes, w11

#550 [VL] Quiz für Java/JVM: Configuration nachreichen
  markdown/java-jvm/configuration.md
Labels: bug, vorlesungen, quizzes, w12

#553 [VL] Quiz für Build: Docker nachreichen
  markdown/building/docker.md
Labels: bug, vorlesungen, quizzes, w12

#554 [VL]: Exams
  config.yaml
  markdown/org/exam.md
  markdown/org/grading.md
Labels: vorlesungen, w13

#555 [VL]: Exams
  data/schedule.yaml
Labels: bug, vorlesungen, w13

#540 [VL]: Collection
  markdown/images/fahrplan.png
  markdown/java-jvm/collections.md
  markdown/java-jvm/images/arraylist.gif
  markdown/java-jvm/images/arraylist.png
  markdown/java-jvm/images/collection.png
  markdown/java-jvm/images/collection.uxf
  markdown/java-jvm/images/collections.png
  markdown/java-jvm/images/collections.uxf
  markdown/java-jvm/images/collections_table.png
  markdown/java-jvm/images/collections_table_vorlage.numbers
  markdown/java-jvm/images/gif_vorlage/arraylist_vorlage.pptx
  markdown/java-jvm/images/gif_vorlage/iterator_vorlage.pptx
  markdown/java-jvm/images/gif_vorlage/linkedlist_vorlage.pptx
  markdown/java-jvm/images/hashmap.png
  markdown/java-jvm/images/hashmap.uxf
  markdown/java-jvm/images/iterator.gif
  markdown/java-jvm/images/iterator.png
  markdown/java-jvm/images/iterator.uxf
  markdown/java-jvm/images/iteratoruml.drawio
  markdown/java-jvm/images/iteratoruml.png
  markdown/java-jvm/images/linkedlist.gif
  markdown/java-jvm/images/linkedlist.png
  markdown/java-jvm/images/map.png
  markdown/java-jvm/images/map.uxf
  markdown/java-jvm/src/collections/hash_example/HashCodeExample.java
  markdown/java-jvm/src/collections/hash_example/Point.java
  markdown/java-jvm/src/collections/iterator_example/BinarySearchTree.java
  markdown/java-jvm/src/collections/iterator_example/InorderIterator.java
  markdown/java-jvm/src/collections/iterator_example/IteratorExample.java
  planung_pm.xlsx
Labels: vorlesungen, neu, w13, high prio
