Repository Programmiermethoden-CampusMinden/Prog2-Lecture, pull requests merged in 2022-04, with the labels that each got.

#366 Aufgaben: Überarbeite Sheet 02
  markdown/assignments/pool_k/sheet02.md
  markdown/assignments/pool_k/tasks/factory_method.md
  markdown/assignments/pool_k/tasks/logging.md
Labels: aufgaben, w1

#292 Vorlesung: Generics: Polymorphie
  markdown/generics/generics-polymorphism.md
  markdown/generics/src/arrays/X.java
Labels: vorlesungen, w3

#337 Add: Konzeptaufgabe Bad Smells und Refactoring
  markdown/assignments/pool_k/tasks/bad_smells-refactoring.md
Labels: aufgaben

#293 Vorlesung: Strategy
  markdown/pattern/images/hunde.png
  markdown/pattern/images/hunde.uxf
  markdown/pattern/images/hunde_strat.png
  markdown/pattern/images/hunde_strat.uxf
  markdown/pattern/images/translator.png
  markdown/pattern/images/translator.uxf
  markdown/pattern/src/SortDefault.java
  markdown/pattern/src/SortOwnCrit.java
  markdown/pattern/src/Studi.java
  markdown/pattern/src/TranslatorExample.java
  markdown/pattern/strategy.md
Labels: vorlesungen, w3

#378 Landing-Page Praktikum: Pools durchnummerieren
  markdown/assignments/_index.md
Labels: bug, vorlesungen, w1

#379 Fahrplan: Dungeon-Starter-Aufgabe verlinken
  data/schedule.yaml
  markdown/assignments/_index.md
  markdown/assignments/pool_concept/_index.md
  markdown/assignments/pool_concept/sheet01.md
  markdown/assignments/pool_concept/sheet02.md
  markdown/assignments/pool_concept/sheet03.md
  markdown/assignments/pool_concept/sheet04.md
  markdown/assignments/pool_concept/sheet05.md
  markdown/assignments/pool_concept/sheet06.md
  markdown/assignments/pool_concept/sheet07.md
  markdown/assignments/pool_concept/sheet08.md
  markdown/assignments/pool_concept/sheet09.md
  markdown/assignments/pool_concept/sheet10.md
  markdown/assignments/pool_concept/tasks/_index.md
  markdown/assignments/pool_concept/tasks/bad_smells-refactoring.md
  markdown/assignments/pool_concept/tasks/factory_method.md
  markdown/assignments/pool_concept/tasks/git_basics.md
  markdown/assignments/pool_concept/tasks/git_branches.md
  markdown/assignments/pool_concept/tasks/junit_basics.md
  markdown/assignments/pool_concept/tasks/logging.md
  markdown/assignments/pool_concept/tasks/mocking.md
  markdown/assignments/pool_dungeon/_index.md
  markdown/assignments/pool_dungeon/group_a/_index.md
  markdown/assignments/pool_dungeon/group_a/charakterklassen.md
  markdown/assignments/pool_dungeon/group_a/crafting.md
  markdown/assignments/pool_dungeon/group_a/dungeon-start.md
  markdown/assignments/pool_dungeon/group_a/fallen.md
  markdown/assignments/pool_dungeon/group_a/freie_aufgabe.md
  markdown/assignments/pool_dungeon/group_a/inventar_text_based.md
  markdown/assignments/pool_dungeon/group_a/skills.md
  markdown/assignments/pool_dungeon/group_a/speichern_und_laden.md
  markdown/assignments/pool_dungeon/group_b/_index.md
  markdown/assignments/pool_dungeon/group_b/boss_monster.md
  markdown/assignments/pool_dungeon/group_b/fernkampf.md
  markdown/assignments/pool_dungeon/group_b/freie_aufgabe.md
  markdown/assignments/pool_dungeon/group_b/gameover.md
  markdown/assignments/pool_dungeon/group_b/magie.md
  markdown/assignments/pool_dungeon/group_b/monster.md
  markdown/assignments/pool_dungeon/group_b/nahkampf.md
  markdown/assignments/pool_dungeon/group_b/schlaue_monster.md
  markdown/assignments/pool_dungeon/group_b/xp.md
  markdown/assignments/pool_dungeon/group_c/_index.md
  markdown/assignments/pool_dungeon/group_c/dialogsystem.md
  markdown/assignments/pool_dungeon/group_c/freie_aufgabe.md
  markdown/assignments/pool_dungeon/group_c/hud.md
  markdown/assignments/pool_dungeon/group_c/inventar_ui.md
  markdown/assignments/pool_dungeon/group_c/item.md
  markdown/assignments/pool_dungeon/group_c/npc.md
  markdown/assignments/pool_dungeon/group_c/quests.md
  markdown/assignments/pool_dungeon/group_c/schatzkiste.md
  markdown/assignments/pool_dungeon/group_c/shop.md
  markdown/assignments/pool_dungeon/group_c/taschen.md
  markdown/org/grading.md
Labels: bug, aufgaben, vorlesungen, w1

#381 Förderung: Hinweis auf Förderung durch DH.NRW einbauen
  README.md
  markdown/_index.md
Labels: vorlesungen, w1

#382 Orga/Fahrplan: Screenshot Excel-Tabelle einbinden
  markdown/_index.md
  markdown/images/fahrplan.png
Labels: enhancement, aufgaben, vorlesungen, w1

#388 Orga: Praktika sind in Präsenz -- die Studis wollen es so
  markdown/_index.md
  markdown/org/grading.md
Labels: bug, aufgaben, vorlesungen, w1

#389 Grading: Theorie:Praxis wieder 50:50
  markdown/org/grading.md
Labels: bug, aufgaben, vorlesungen, w1

#392 fix warning regarding missing gincltex package
  .github/actions/alpine-pandoc-hugo/install-packages.sh
Labels: bug, vorlesungen

#391 Add: Konzeptaufgabe JUnit Advanced Bank
  markdown/assignments/pool_concept/tasks/junit_advanced_bank.md
Labels: aufgaben, neu, w4, konzept

#394 Add: Konzeptaufgabe JUnit Advanced RSV
  markdown/assignments/pool_concept/tasks/junit_advanced_rsv.md
Labels: aufgaben, neu, w4, konzept

#397 Tutorium: neuer Raum ist der B70
  markdown/_index.md
Labels: vorlesungen

#303 Vorlesung: Build: Gradle
  markdown/building/gradle.md
Labels: vorlesungen, w4

#398 Vorlesung: Build: Continuous Integration (Follow-Up zu #308)
  markdown/building/ci.md
  markdown/building/images/ci.png
  markdown/building/images/screenshot-githubci-job.png
  markdown/building/images/screenshot-githubci-triggeredworkflow.png
  markdown/building/images/screenshot-githubci-workflows.png
  markdown/building/images/screenshot-gitlabci-job.png
  markdown/building/images/screenshot-gitlabci-pipelines.png
  markdown/building/images/screenshot-gitlabci-triggeredpipeline.png
  markdown/building/images/screenshot_github_actions.png
  markdown/building/images/screenshot_github_settings_actions.png
  markdown/building/images/screenshot_github_settings_permissions.png
Labels: vorlesungen, w4

#399 rename desktop to dungeon-starter
  markdown/assignments/pool_dungeon/group_a/dungeon-start.md
Labels: aufgaben

#400 [Bug] Aufgabe Logging: Vertausche Methodenaufrufe (fix typo)
  markdown/assignments/pool_concept/tasks/logging.md
Labels: bug, aufgaben, w1

#401 VL Continuous Integration: Nutze korrekte Begriffe bei GitLab/GitHub
  markdown/building/ci.md
Labels: enhancement, aufgaben, w4

#393 Add Konzeptaufgabe: Swing
  markdown/assignments/pool_concept/tasks/swing.md
Labels: aufgaben

#294 Vorlesung: Testing: JUnit Basics
  markdown/testing/images/junitErgebnis.png
  markdown/testing/images/junitIgnore.png
  markdown/testing/images/newJUnit.png
  markdown/testing/images/swfehler.png
  markdown/testing/junit-basics.md
  markdown/testing/src/junit4/MyTestSuite4.java
  markdown/testing/src/junit4/Studi.java
  markdown/testing/src/junit4/Sum.java
  markdown/testing/src/junit4/SumTestConstructor.java
  markdown/testing/src/junit4/SumTestParameters.java
  markdown/testing/src/junit4/Test4.java
  markdown/testing/src/junit4/TestAssume.java
  markdown/testing/src/junit5/MyTestSuite5.java
  markdown/testing/src/junit5/Test5.java
  markdown/testing/src/junit5/TestMethodSource.java
  markdown/testing/src/junit5/TestValueSource.java
  markdown/testing/testing-intro.md
Labels: vorlesungen, w4

#299 Vorlesung: Testing: Testfälle erstellen
  markdown/testing/images/aequivalenzklassen.odg
  markdown/testing/images/aequivalenzklassen.png
  markdown/testing/images/grenzwerte.png
  markdown/testing/testcases.md
Labels: vorlesungen, w4

#405 Aufgaben: Überarbeite Sheet 03
  markdown/assignments/pool_concept/sheet03.md
  markdown/assignments/pool_concept/tasks/generics1.md
  markdown/assignments/pool_concept/tasks/generics2.md
Labels: aufgaben, w3

#412 Fix #406: Beispiel-Lerntagebuch lädt das UML-Diagramm nicht
  markdown/org/images/tagebuch_uml.png
  markdown/org/lerntagebuch_beispiel.md
Labels: bug, aufgaben, vorlesungen, w1

#413 Fix 409: Ergänze Hinweise auf Blatt01
  markdown/assignments/pool_concept/sheet01.md
Labels: aufgaben, w1

#414 Fix #410: Ergänze Erinnerung zu Javadoc und Logging auf Blatt02
  markdown/assignments/pool_concept/sheet02.md
Labels: aufgaben, w1

#415 Fix #408: Dungeon-Start: Ergänze Erinnerung an Lerntagebuch
  markdown/assignments/pool_dungeon/group_a/dungeon-start.md
Labels: aufgaben, w1

#416 Fix #407: Dungeon-Starter: ergänze Punkteverteilung
  markdown/assignments/pool_dungeon/group_a/dungeon-start.md
Labels: aufgaben, w1

#417 Schedule: ergänze Testing Intro
  data/schedule.yaml
Labels: bug, vorlesungen, w4

#301 Vorlesung: Coding: TDD
  markdown/coding/images/tdd.odg
  markdown/coding/images/tdd.png
  markdown/coding/src/tdd/PasswordChecker.java
  markdown/coding/src/tdd/PasswordCheckerTest.java
  markdown/coding/src/tdd/anforderungen.md
  markdown/coding/tdd.md
Labels: vorlesungen, w4

#321 Vorlesung: Coding: Smells
  data/schedule.yaml
  markdown/coding/codingrules.md
  markdown/coding/smells.md
Labels: vorlesungen, w5

#419 Add: Konzeptaufgabe: Gradle
  markdown/assignments/pool_concept/tasks/gradle.md
Labels: aufgaben, w4

#418 Aufgaben: Überarbeite Sheet 04
  markdown/assignments/pool_concept/sheet04.md
  markdown/assignments/pool_concept/tasks/junit_advanced_rsv.md
  markdown/assignments/pool_concept/tasks/junit_basics.md
Labels: aufgaben, w4

#420 Fix Web: make link in B04 visible and hide empty Coding Rules lecture
  markdown/assignments/pool_concept/tasks/gradle.md
  markdown/coding/codingrules.md
Labels: bug, aufgaben, vorlesungen, w4

#421 Aufgaben: Überarbeite Sheet 05
  markdown/assignments/pool_concept/sheet05.md
  markdown/assignments/pool_concept/tasks/mocking.md
Labels: aufgaben, w5

#424 Fix #423: Dungeon Task A:Crafting should be worth 5 pts
  markdown/assignments/pool_dungeon/group_a/crafting.md
Labels: bug, aufgaben

#425 Add: Konzeptaufgabe Observer Pattern
  markdown/assignments/pool_concept/tasks/observer_pattern.md
Labels: aufgaben, w5

#322 Vorlesung: Coding: Refactoring
  data/schedule.yaml
  markdown/coding/refactoring.md
  markdown/coding/src/refactoring/Kurs.java
  markdown/coding/src/refactoring/KursTest.java
  markdown/coding/src/refactoring/Person.java
  markdown/coding/src/refactoring/PersonTest.java
  markdown/coding/src/refactoring/Studi.java
  markdown/coding/src/refactoring/StudiTest.java
  markdown/images/fahrplan.png
Labels: vorlesungen, w5

#403 Vorlesung: Coding: Coding-Rules
  markdown/coding/codingrules.md
  markdown/coding/smells.md
  markdown/coding/src/checkstyle.xml
  markdown/coding/src/checkstyle/.gitattributes
  markdown/coding/src/checkstyle/.gitignore
  markdown/coding/src/checkstyle/build.gradle
  markdown/coding/src/checkstyle/checkstyle.xml
  markdown/coding/src/checkstyle/gradle/wrapper/gradle-wrapper.jar
  markdown/coding/src/checkstyle/gradle/wrapper/gradle-wrapper.properties
  markdown/coding/src/checkstyle/gradlew
  markdown/coding/src/checkstyle/gradlew.bat
  markdown/coding/src/checkstyle/src/main/java/wuppie/deeplearning/strategy/MyWuppieStudi.java
  markdown/coding/src/formatter/.gitattributes
  markdown/coding/src/formatter/.gitignore
  markdown/coding/src/formatter/build.gradle
  markdown/coding/src/formatter/gradle.properties
  markdown/coding/src/formatter/gradle/wrapper/gradle-wrapper.jar
  markdown/coding/src/formatter/gradle/wrapper/gradle-wrapper.properties
  markdown/coding/src/formatter/gradlew
  markdown/coding/src/formatter/gradlew.bat
  markdown/coding/src/formatter/src/main/java/wuppie/deeplearning/strategy/MyWuppieStudi.java
  markdown/coding/src/formatter/src/main/java/wuppie/deeplearning/strategy/MyWuppieStudi.java_orig
  markdown/coding/src/spotbugs/.gitattributes
  markdown/coding/src/spotbugs/.gitignore
  markdown/coding/src/spotbugs/build.gradle
  markdown/coding/src/spotbugs/gradle/wrapper/gradle-wrapper.jar
  markdown/coding/src/spotbugs/gradle/wrapper/gradle-wrapper.properties
  markdown/coding/src/spotbugs/gradlew
  markdown/coding/src/spotbugs/gradlew.bat
  markdown/coding/src/spotbugs/src/main/java/wuppie/deeplearning/strategy/MyWuppieStudi.java
Labels: vorlesungen, w5

#427 Update Schedule: move TDD to KW19
  data/schedule.yaml
  markdown/images/fahrplan.png
  planung_pm.xlsx
Labels: vorlesungen
