Repository Programmiermethoden-CampusMinden/Prog2-Lecture, pull requests merged in 2023-03, with the labels that each got.

#615 [TOOL] Switch to pandoc-lecture github container action
  .github/actions/alpine-pandoc-hugo/Dockerfile
  .github/actions/alpine-pandoc-hugo/Makefile
  .github/actions/alpine-pandoc-hugo/action.yml
  .github/actions/alpine-pandoc-hugo/install-packages.sh
  .github/workflows/hugo.yaml
  .github/workflows/slides.yaml
Labels: enhancement, pandoc

#616 Update landing page
  config.yaml
  data/schedule.yaml
  markdown/_index.md
  markdown/assignments/pool_concept/_index.md
  markdown/assignments/pool_concept/sheet01.md
  markdown/org/exams.md
  markdown/org/faq.md
  markdown/org/grading.md
  markdown/org/images/howtofeedback1.png
  markdown/org/images/howtofeedback2.png
  markdown/org/images/howtofeedback3.png
  markdown/org/images/howtofeedback4.png
  markdown/org/images/howtofeedback5.png
  markdown/org/resources.md
  markdown/org/schedule.md
  markdown/org/syllabus.md
Labels: bug, vorlesungen, überarbeiten

#628 Credits: replace Hugo-Lecture w/ pandoc-lecture
  CREDITS.md
Labels: bug

#633 [VL] Use 'href' key/value pair in 'bsp' span
  markdown/building/ant.md
  markdown/building/docker.md
  markdown/building/maven.md
  markdown/coding/codingrules.md
  markdown/coding/logging.md
  markdown/coding/smells.md
  markdown/frameworks/intro.md
  markdown/generics/bounds-wildcards.md
  markdown/generics/classes-methods.md
  markdown/generics/generics-polymorphism.md
  markdown/git/remotes.md
  markdown/gui/basics.md
  markdown/gui/events.md
  markdown/gui/java2d.md
  markdown/gui/layouts.md
  markdown/gui/tables.md
  markdown/gui/widgets.md
  markdown/java-jvm/annotations.md
  markdown/java-jvm/collections.md
  markdown/java-jvm/configuration.md
  markdown/java-jvm/enums.md
  markdown/java-jvm/exceptions.md
  markdown/java-jvm/reflection.md
  markdown/java-jvm/regexp.md
  markdown/java-jvm/serialisation.md
  markdown/modern-java/defaultmethods.md
  markdown/modern-java/lambdas.md
  markdown/modern-java/methodreferences.md
  markdown/modern-java/optional.md
  markdown/modern-java/stream-api.md
  markdown/org/syllabus.md
  markdown/pattern/factory-method.md
  markdown/pattern/observer.md
  markdown/pattern/singleton.md
  markdown/pattern/strategy.md
  markdown/pattern/visitor.md
  markdown/testing/junit-basics.md
  markdown/testing/mockito.md
  markdown/testing/testcases.md
  markdown/threads/highlevel.md
  markdown/threads/intro.md
  markdown/threads/synchronisation.md
Labels: bug, vorlesungen, pandoc

#640 [HUGO] Ersetze altes Logo durch neues Dungeon-Katzen-Logo
  static/images/logo.png
Labels: bug, vorlesungen, pandoc

#644 [ORGA] Erstelle erste Planung für S23
  data/schedule.yaml
  markdown/_index.md
  markdown/assignments/_index.md
  markdown/frameworks/dungeon.md
  markdown/frameworks/ecs.md
  markdown/git/worktree.md
  markdown/images/fahrplan.png
  markdown/modern-java/sealed.md
  markdown/org/exams.md
  markdown/org/faq.md
  markdown/org/grading.md
  markdown/org/images/fahrplan.png
  markdown/org/konzeptskizze_beispiel.md
  markdown/org/planung_pm.xlsx
  markdown/org/resources.md
  markdown/org/syllabus.md
  markdown/pattern/dependency.md
  markdown/testing/bdd.md
  markdown/testing/coverage.md
  planung_pm.xlsx
Labels: aufgaben, vorlesungen, überarbeiten, high prio

#662 [Action] Fix MLC action
  .github/workflows/.mlc_config.json
  .github/workflows/mlc.yaml
  .github/workflows/mlc_config.json
Labels: bug, pandoc

#664 Another attempt to fix MLC configuration
  .github/workflows/.mlc_config.json
Labels: bug

#663 [VL] überprüfe Links in Markdown
  markdown/assignments/pool_concept/tasks/gradle.md
  markdown/assignments/pool_concept/tasks/regexp.md
  markdown/assignments/pool_dungeon/group_a/dungeon-start.md
  markdown/assignments/pool_dungeon/group_c/hud.md
  markdown/building/ci.md
  markdown/coding/codingrules.md
  markdown/frameworks/intro.md
  markdown/java-jvm/annotations.md
  markdown/java-jvm/collections.md
  markdown/java-jvm/enums.md
  markdown/java-jvm/exceptions.md
  markdown/modern-java/optional.md
  markdown/modern-java/stream-api.md
  markdown/org/images/ilias_upload.png
  markdown/org/resources.md
  markdown/pattern/observer.md
  markdown/pattern/strategy.md
  markdown/testing/junit-basics.md
  markdown/testing/mockito.md
  markdown/threads/highlevel.md
  pm.bib
Labels: bug, vorlesungen

#665 Action: Remove MLC workflow
  .github/workflows/.mlc_config.json
  .github/workflows/mlc.yaml
Labels: bug, pandoc

#666 [GitHub] add codeowners
  .github/CODEOWNERS
Labels: bug, pandoc

#667 [Orga] Update Fahrplan - Zähle Vorlesungszeit-Wochen
  data/schedule.yaml
  markdown/org/images/fahrplan.png
  markdown/org/planung_pm.xlsx
Labels: aufgaben, vorlesungen, überarbeiten

#668 [ORG] add overview table to assignment landing page
  markdown/assignments/_index.md
Labels: aufgaben, neu, überarbeiten, high prio

#670 [VL] Ergänze Hinweise auf nette ShPD-Einführungsvideos
  markdown/assignments/_index.md
  markdown/frameworks/dungeon.md
  markdown/org/faq.md
  markdown/org/resources.md
Labels: aufgaben, vorlesungen

#671 [Org] add link to Java Programmer Roadmap
  markdown/org/resources.md
Labels: enhancement, vorlesungen

#672 [Schedule] Gastvortrag zu JUnit/Mocking in der Praxis
  data/schedule.yaml
Labels: vorlesungen, überarbeiten

#673 [FAQ] Hinweis auf nicht ECS-konformes Beispiel der Konzeptskizze
  markdown/org/faq.md
Labels: aufgaben, vorlesungen, überarbeiten

#674 [FAQ] Freie Aufgaben können mehrfach gewählt werden
  markdown/org/faq.md
Labels: aufgaben, überarbeiten

#675 [FAQ] formuliere Bounty-Aufgaben klarer
  markdown/org/faq.md
Labels: aufgaben, vorlesungen, überarbeiten

#680 [FAQ] Gleiche FAQ und Grading ab
  markdown/org/faq.md
  markdown/org/grading.md
Labels: vorlesungen, überarbeiten
